Raise proper error if host is nil
In case the host was nil then we got some
`NoMethodError: undefined method 'role' for nil:NilClass`. This Commit
raises a proper error so it is easier to fix issues around this.