Fix status_controller_spec
"render_views" and "render_template" have been moved to a separate gem,
per this error message:

> NoMethodError: assert_template has been extracted to a gem. To
> continue using it, add `gem 'rails-controller-testing'` to your
> Gemfile.

Adding the gem fixed the errors in "status_controller_spec.rb".